'use strict';
const { launch } = require('./headless');
const BASE = process.env.VB_URL || 'http://127.0.0.1:5504/index.html';

(async()=>{
  const b=await launch();
  try{
    await b.goto(BASE,1800);
    const r=await b.eval(`
      const px=e=>e?{border:getComputedStyle(e).borderTopWidth,shadow:getComputedStyle(e).boxShadow,outline:getComputedStyle(e).outline,display:getComputedStyle(e).display,opacity:getComputedStyle(e).opacity}:null;
      const pseudo=e=>e?{before:{content:getComputedStyle(e,'::before').content,border:getComputedStyle(e,'::before').borderTopWidth,shadow:getComputedStyle(e,'::before').boxShadow,opacity:getComputedStyle(e,'::before').opacity},after:{content:getComputedStyle(e,'::after').content,border:getComputedStyle(e,'::after').borderTopWidth,shadow:getComputedStyle(e,'::after').boxShadow,opacity:getComputedStyle(e,'::after').opacity}}:null;
      const root=document.getElementById('scr-battle');
      document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));
      root.classList.add('active'); document.body.className='';
      const mk=(id,lane,slot)=>({id,name:id,lane,slot,atk:3,hp:50,maxHp:50,color:'赤',keywords:[],desc:'',_panelSummoned:true});
      G.enemies=new Array(14).fill(null); G.enemies[0]=mk('E1','front',0);
      G.allies=new Array(14).fill(null); G.allies[0]=mk('A1','front',0);
      renderField('f-enemy',G.enemies,true); renderField('f-ally',G.allies,false);
      await new Promise(r=>requestAnimationFrame(r));
      beginBattleMotion();
      const motion=playAttackMotion(G.allies[0],G.enemies[0],false,null,{stopRatio:.25,firstDuration:260,secondDuration:360,returnDuration:420});
      await new Promise(r=>setTimeout(r,120));
      const clone=document.querySelector('.attack-motion-clone');
      const attackFrame=clone?.querySelector('.unit-frame-layer');
      const attack=Object.assign(px(attackFrame)||{},{classes:clone?.className||'',inline:attackFrame?.getAttribute('style')||''});
      await motion; endBattleMotion();
      const drag=document.createElement('div'); drag.className='card';
      const dragFrame=document.createElement('div'); dragFrame.className='unit-frame-layer'; drag.appendChild(dragFrame);
      document.body.appendChild(drag); drag.classList.add('dragging');
      const dragState=px(dragFrame);
      _createDragGhost(drag);
      const ghost=document.querySelector('.drag-ghost');
      const ghostFrame=ghost?.querySelector('.unit-frame-layer');
      const ghostState=Object.assign(px(ghostFrame)||{},{classes:ghost?.className||'',inline:ghostFrame?.getAttribute('style')||'',pseudo:pseudo(ghost)});
      _removeDragGhost(); drag.remove();
      const specialGhostSrc=document.createElement('div'); specialGhostSrc.className='card character-card panel-character-card'; specialGhostSrc.dataset.mapBoard='summon';
      const specialGhostSrcFrame=document.createElement('span'); specialGhostSrcFrame.className='character-frame-layer'; specialGhostSrc.appendChild(specialGhostSrcFrame); document.body.appendChild(specialGhostSrc);
      _createDragGhost(specialGhostSrc);
      const specialGhost=document.querySelector('.drag-ghost');
      const specialGhostFrame=specialGhost?.querySelector('.character-frame-layer');
      const specialGhostState=Object.assign(px(specialGhostFrame)||{},{pseudo:pseudo(specialGhost)});
      _removeDragGhost(); specialGhostSrc.remove();
      const special=document.createElement('div'); special.className='card character-card panel-character-card'; special.dataset.mapBoard='summon';
      const charFrame=document.createElement('span'); charFrame.className='character-frame-layer';
      const board=document.createElement('span'); board.className='board-frame-layer';
      const boundary=document.createElement('span'); boundary.className='map-boundary-layer';
      special.append(charFrame,board,boundary); document.body.appendChild(special);
      _hideDragSourceParts(special);
      const specialState={frame:px(charFrame),board:px(board),boundary:px(boundary)}; special.remove();
      const enchant=document.createElement('div'); enchant.className='card enchantment-card';
      const enchantFrame=document.createElement('span'); enchantFrame.className='character-frame-layer';
      enchant.appendChild(enchantFrame); document.body.appendChild(enchant); _hideDragSourceParts(enchant);
      const enchantState={frame:px(enchantFrame),after:getComputedStyle(enchant,'::after').content}; enchant.remove();
      const specialEnchant=document.createElement('div'); specialEnchant.className='card enchantment-card'; specialEnchant.dataset.mapBoard='summon';
      const specialEnchantFrame=document.createElement('span'); specialEnchantFrame.className='character-frame-layer';
      const specialEnchantBoard=document.createElement('span'); specialEnchantBoard.className='board-frame-layer';
      const specialEnchantBoundary=document.createElement('span'); specialEnchantBoundary.className='map-boundary-layer';
      specialEnchant.append(specialEnchantFrame,specialEnchantBoard,specialEnchantBoundary); document.body.appendChild(specialEnchant); _hideDragSourceParts(specialEnchant);
      const specialEnchantState={frame:px(specialEnchantFrame),board:px(specialEnchantBoard),boundary:px(specialEnchantBoundary)}; specialEnchant.remove();
      const hs=document.createElement('div'); hs.id='hand-slots'; hs.className='unit-equip-slots';
      const ench=document.createElement('div'); ench.className='card'; ench.dataset.mapBoard='summon'; ench.classList.add('dragging'); hs.appendChild(ench); document.body.appendChild(hs);
      const enchantBorder=getComputedStyle(ench,'::after').borderTopWidth; hs.remove();
      const handDrag=document.createElement('div'); handDrag.className='card character-card panel-character-card dragging';
      const handFrame=document.createElement('span'); handFrame.className='character-frame-layer'; handDrag.appendChild(handFrame);
      const handGlow=document.createElement('span'); handGlow.className='card-glow-layer'; handDrag.appendChild(handGlow); hs.appendChild(handDrag); document.body.appendChild(hs);
      const handDragState={card:px(handDrag),pseudo:pseudo(handDrag),frame:px(handFrame)}; hs.remove();
      const rewardHost=document.createElement('div'); rewardHost.id='battle-order-row';
      const rewardDrag=document.createElement('div'); rewardDrag.className='rew-card dragging'; rewardHost.appendChild(rewardDrag); document.body.appendChild(rewardHost);
      const rewardDragState={card:px(rewardDrag),pseudo:pseudo(rewardDrag)}; rewardHost.remove();
      const dark=document.createElement('div'); dark.className='card invalid-battle-position';
      const darkFrame=document.createElement('span'); darkFrame.className='character-frame-layer'; dark.appendChild(darkFrame); hs.appendChild(dark); document.body.appendChild(hs);
      const darkState={frame:px(darkFrame),filter:getComputedStyle(darkFrame).filter}; hs.remove();
      const darkDrag=document.createElement('div'); darkDrag.className='card invalid-battle-position dragging';
      const darkDragFrame=document.createElement('span'); darkDragFrame.className='character-frame-layer';
      const darkDragBoard=document.createElement('span'); darkDragBoard.className='board-frame-layer';
      darkDrag.append(darkDragFrame,darkDragBoard); hs.appendChild(darkDrag); document.body.appendChild(hs);
      const darkDragPseudo=pseudo(darkDrag);
      const darkDragLayers={frame:getComputedStyle(darkDragFrame).filter,board:getComputedStyle(darkDragBoard).filter}; hs.remove();
      const anchor=document.createElement('div'); anchor.style.cssText='position:fixed;left:20px;top:20px;width:40px;height:40px'; document.body.appendChild(anchor);
      const keywordTip=document.getElementById('keyword-tooltip'); keywordTip.style.display='block'; keywordTip.style.position='fixed'; keywordTip.style.left='20px'; keywordTip.style.top='20px'; keywordTip.style.width='100px'; keywordTip.style.height='30px';
      _openRewardActionTooltip(anchor,'アイテム','説明',[{label:'使う',disabled:true}]);
      const actionTip=document.getElementById('kw-tooltip');
      const keywordPlacement={actionBottom:actionTip.getBoundingClientRect().bottom,keywordTop:keywordTip.getBoundingClientRect().top,gap:keywordTip.getBoundingClientRect().top-actionTip.getBoundingClientRect().bottom};
      anchor.remove(); _closeItemUseConfirm(); keywordTip.style.display='none';
      return {attack,drag:dragState,ghost:ghostState,specialGhost:specialGhostState,handDrag:handDragState,rewardDrag:rewardDragState,special:specialState,enchant:enchantState,specialEnchant:specialEnchantState,enchantBorder,dark:darkState,darkDragPseudo,darkDragLayers,keywordPlacement};
    `);
    console.log(JSON.stringify(r));
  }finally{ await b.close(); }
})().catch(e=>{ console.error(e.stack||e); process.exitCode=1; });
