'use strict';
const {launch}=require('./parity/headless');
(async()=>{
  const b=await launch();
  try{
    await b.goto('http://127.0.0.1:5500/index.html');
    await b.waitFor('typeof SaveRun!=="undefined"&&PANEL_POOL.length>20',20000);
    const result=await b.eval(`
      const checks=[];
      const check=(name,value)=>{if(!value) throw new Error(name);checks.push(name);};
      window.alert=message=>{window.__saveAlert=message;};
      _playVillageEnterIntro=async build=>build();
      startGame(false);
      const original=loadRun();
      const profileKey=SaveStorage.key('profile','current');
      const runKey=SaveStorage.key('run','current');
      const unknown=()=>PANEL_POOL.find(c=>!SaveProfile.load().cards[SaveProfile.identity(c)?.id]&&c.category==='エンチャント');
      const card=makePanel(unknown().id),ref=SaveProfile.identity(card);
      _openWaveFormation();
      _rewCards=[card];card._isOriginalReward=true;renderRewCards();
      await new Promise(r=>setTimeout(r,60));
      check('報酬候補の実表示でseen=true',SaveProfile.load().cards[ref.id]?.seen);
      check('候補を取らなければacquired=false',SaveProfile.load().cards[ref.id]?.acquired===false);
      card.directions=['up','right','down','left'];
      _rewFreePickDone=false;
      const occupied=G.mainBoard.findIndex(Boolean),cols=5;
      const target=[occupied-cols,occupied+1,occupied+cols,occupied-1].find(i=>i>=0&&i<G.mainBoard.length&&!G.mainBoard[i]&&Math.abs(i%cols-occupied%cols)+Math.abs(Math.floor(i/cols)-Math.floor(occupied/cols))===1);
      takeRewCard(0,target);
      check('報酬の正式取得でacquired=true',SaveProfile.load().cards[ref.id]?.acquired);
      const transient=unknown(),tid=SaveProfile.identity(transient).id;
      G.allies.push({...transient,hp:3,maxHp:3,atk:2,_panelSummoned:true});
      SaveProfile.owned();markCardSeen(transient);
      check('一時召喚はseenのみでacquiredにしない',SaveProfile.load().cards[tid]?.seen&&!SaveProfile.load().cards[tid]?.acquired);
      const debugCard=unknown(),beforeDebug=JSON.stringify(SaveProfile.load());
      G._debugMode=true;markCardSeen(debugCard);markCardAcquired(debugCard);SaveProfile.owned();
      check('デバッグ操作はコレクションを解放しない',JSON.stringify(SaveProfile.load())===beforeDebug);
      G._debugMode=false;G._testBattleMode=true;markCardAcquired(debugCard);G._testBattleMode=false;
      G._libraryTutorialActive=true;markCardSeen(debugCard);G._libraryTutorialActive=false;
      check('試験戦闘とチュートリアルも除外',JSON.stringify(SaveProfile.load())===beforeDebug);
      const item=ITEM_POOL[0];markCardSeen(item);markCardAcquired(item);
      check('数字No.のアイテムはI001等の正式IDで管理',SaveProfile.load().items[SaveProfile.identity(item).id]?.acquired);
      const ring=RING_POOL[0];markCardSeen(ring);markCardAcquired(ring);
      check('指輪の発見・取得を分離保存',SaveProfile.load().rings[SaveProfile.identity(ring).id]?.acquired);
      let writes=0;SaveStorage.setAdapter({getItem:k=>localStorage.getItem(k),setItem:(k,v)=>{writes++;localStorage.setItem(k,v)},removeItem:k=>localStorage.removeItem(k)});
      for(let i=0;i<100;i++){markCardSeen(card);markCardAcquired(card);}
      check('記録済みカード100回の表示・取得で追加書込なし',writes===0);SaveStorage.setAdapter(null);
      G._wave=1;G._waveStage=5;G._waveVillage=true;openMapVillage({intro:true});const townStart=loadRun();showScreen('battle');openMapShop();
      await new Promise(r=>setTimeout(r,80));
      const stock=_rewCards.filter(Boolean);
      const stockState=stock.map(c=>({id:SaveProfile.identity(c)?.id,seen:!!SaveProfile.load().cards[SaveProfile.identity(c)?.id]?.seen}));
      check('ショップ陳列で全商品seen=true '+JSON.stringify(stockState),stock.length>0&&stockState.every(x=>x.id&&x.seen));
      const shopIdx=_rewCards.findIndex(Boolean),purchased=_rewCards[shopIdx];purchased.directions=['up','right','down','left'];
      G.gold=10000;takeRewCard(shopIdx,G.mainBoard.findIndex(c=>!c));
      await new Promise(r=>setTimeout(r,80));
      check('ショップ購入でacquired=true',SaveProfile.load().cards[SaveProfile.identity(purchased).id]?.acquired);
      const town=loadRun();check('街途中の購入はrun saveへ書かない',town.state.choices._waveShopStock[1][shopIdx]!==null);
      openMapVillage();const departOriginal=departWithWorldMap;departWithWorldMap=()=>{};G._villageIntroPlaying=false;villageDepart();const committedTown=loadRun();departWithWorldMap=departOriginal;SaveRun.lockInput(false);document.body.classList.remove('village-departing');
      check('街の出発確定で購入結果を正式保存',committedTown.checkpoint.type==='town'&&committedTown.state.choices._waveShopStock[1][shopIdx]===null);
      SaveRun.saveRun(townStart);
      SaveRun.restoreRunState(townStart);openMapVillage({restoreCheckpoint:true});showScreen('battle');openMapShop();
      check('街復元で購入前の同じ商品へ戻る',_rewCards[shopIdx]!==null&&JSON.stringify(_rewCards)===JSON.stringify(townStart.state.choices._waveShopStock[1]));
      openMapVillage({restoreCheckpoint:true});const current=loadRun();
      SaveRun.restoreRunState(current);G._waveVillage=false;G._isWaveAltar=false;G._isVillageMenu=false;G._isShop=false;G._isForge=false;G._isItemShop=false;G._isRingExchange=false;G.phase=null;G._waveRewardCount=3;
      goToReward({checkpoint:true});const rewardStart=loadRun(),rewardCards=JSON.stringify(rewardStart.state.reward.cards),rewardGold=rewardStart.state.player.gold;
      G.gold+=777;_rewCards.shift();
      await SaveRun.continueRun();
      check('報酬途中操作を開始状態へ巻き戻す',loadRun().checkpoint.type==='reward'&&G.gold===rewardGold&&JSON.stringify(_rewCards)===rewardCards);
      check('報酬直接再開では戦闘再開UIを出さない',!document.body.classList.contains('run-resume-active'));
      G.gold+=55;const flowOriginal=_startWaveFlowNext;_startWaveFlowNext=()=>true;chooseMoveInline('battle');await new Promise(r=>setTimeout(r,950));_startWaveFlowNext=flowOriginal;SaveRun.lockInput(false);
      check('報酬の戦闘開始確定で途中変更を正式保存',loadRun().checkpoint.type==='reward'&&loadRun().state.player.gold===rewardGold+55);
      SaveRun.restoreRunState(current);G._wave=1;G._waveStage=10;G._waveVillage=true;G.phase=null;openMapVillage({intro:true,tower:true});
      const towerStart=loadRun(),towerOffer=JSON.stringify(towerStart.state.choices._waveRingExchange?.[1]?.offer||[]);
      check('塔到着時にtypeと祭壇候補を保存',towerStart.checkpoint.type==='tower'&&towerOffer!=='[]');
      G._waveRingExchange[1].offer=[];G.gold+=333;
      await SaveRun.continueRun();
      check('塔途中操作を同じ候補の開始状態へ巻き戻す',G.gold===towerStart.state.player.gold&&JSON.stringify(G._waveRingExchange[1].offer)===towerOffer);
      check('塔直接再開では戦闘再開UIを出さない',!document.body.classList.contains('run-resume-active'));
      for(const kind of ['elite','boss']){
        const route=_journeyRouteForScene(kind==='boss'?5:2),idx=route.indexOf(kind);
        G._wave=kind==='boss'?5:2;G._waveStage=idx+1;
        _syncRewardJourneyUi({root:document.getElementById('run-resume-journey-ui'),exactCurrent:true,resume:true});
        const marked=[...document.querySelectorAll('#run-resume-journey-ui .journey-node')].findIndex(n=>n.classList.contains('run-resume-current'));
        check(kind+'戦再開では該当マスを点滅対象にする',idx>=0&&marked===idx);
      }
      const legacy=SaveRun.copy(current);legacy.saveVersion=1;legacy.checkpoint='village';
      check('旧v1の街セーブをv2 checkpointへ移行',SaveRun.validate(legacy).checkpoint.type==='town');
      const checkRejected=(name,mutate)=>{const bad=SaveRun.copy(current);mutate(bad);let rejected=false;try{SaveRun.validate(bad);}catch(e){rejected=true;}check(name,rejected);};
      checkRejected('未来saveVersionを拒否',s=>s.saveVersion=999);
      checkRejected('NaNを拒否',s=>s.state.player.gold=NaN);
      checkRejected('Infinityを拒否',s=>s.state.player.gold=Infinity);
      checkRejected('存在しない現在地を拒否',s=>s.state.location.stage=999);
      checkRejected('不正なカードIDを拒否',s=>s.state.player.mainBoard[0]={id:'invalid-card'});
      checkRejected('必須フィールド欠落を拒否',s=>delete s.state.player.mainBoard);
      const mem=new Map(),backend={getItem:k=>mem.get(k)??null,setItem:(k,v)=>mem.set(k,v),removeItem:k=>mem.delete(k)};
      SaveStorage.setAdapter(backend);SaveRun.saveRun(current);
      const newer=SaveRun.copy(current);newer.state.player.gold++;SaveRun.saveRun(newer);
      mem.set(runKey,'{broken');
      check('破損currentから正常backupへ復旧',loadRun().state.player.gold===current.state.player.gold);
      mem.set(SaveStorage.key('run','backup'),'{also broken');
      check('両世代破損でも例外を外へ出さず起動継続',loadRun()===null);
      mem.clear();SaveRun.saveRun(current);const oldRaw=mem.get(runKey);
      SaveStorage.setAdapter({...backend,setItem:(k,v)=>{if(k===runKey)throw new Error('テスト容量不足');backend.setItem(k,v);}});
      let failed=false;try{SaveRun.saveRun(newer);}catch(e){failed=true;}
      check('新current保存失敗でも旧currentが残る',failed&&mem.get(runKey)===oldRaw);
      SaveStorage.setAdapter(backend);
      const future=SaveRun.copy(current);future.saveVersion=999;mem.set(runKey,JSON.stringify(future));
      let protectedFuture=false;try{SaveRun.saveRun(newer);}catch(e){protectedFuture=e.code==='SAVE_FUTURE';}
      check('未来版セーブを上書きしない',protectedFuture&&JSON.parse(mem.get(runKey)).saveVersion===999);
      mem.clear();SaveRun.saveRun(current);
      const prof=SaveRun.copy(SaveProfile.load());SaveStorage.write('profile',prof,SaveProfile.validate);SaveStorage.write('profile',prof,SaveProfile.validate);
      mem.set(profileKey,'{broken');check('profileもbackupでコレクションを復旧',!!SaveStorage.read('profile',SaveProfile.validate)?.data.cards[ref.id]?.acquired);
      SaveRun.restoreRunState(current);const beforeEnd=mem.get(runKey);
      SaveStorage.setAdapter({...backend,setItem:(k,v)=>{if(k===profileKey)throw new Error('テストprofile保存失敗');backend.setItem(k,v);}});
      SaveRun.finish('gameover');check('profile更新失敗時はrunを削除しない',mem.get(runKey)===beforeEnd);
      SaveStorage.setAdapter(backend);SaveRun.finish('gameover');
      check('ゲームオーバー確定でrunの両世代を削除',!mem.has(runKey)&&!mem.has(SaveStorage.key('run','backup')));
      check('run削除後もprofileとコレクションが残る',JSON.parse(mem.get(profileKey)).cards[ref.id]?.acquired);
      SaveRun.restoreRunState(current);SaveRun.begin();const clearSave=SaveRun.buildRunSave('town');SaveRun.saveRun(clearSave);SaveRun.finish('clear');
      check('ゲームクリア確定でもrun削除・profile維持',!mem.has(runKey)&&mem.has(profileKey));
      SaveStorage.setAdapter(null);
      SaveRun.restoreRunState(original);
      let intro=0;_playBattleStartIntro=async()=>{intro++;return 'normal';};
      SaveStorage.setAdapter({getItem:k=>localStorage.getItem(k),setItem:()=>{throw new Error('テストrun保存失敗');},removeItem:k=>localStorage.removeItem(k)});
      _startWaveFlowNext();
      for(let i=0;i<100&&!window.__saveAlert;i++) await new Promise(r=>setTimeout(r,50));
      check('保存失敗で戦闘演出は始まらずエラー表示',intro===0&&window.__saveAlert?.includes('セーブに失敗'));
      SaveStorage.setAdapter(null);
      return checks;
    `);
    result.forEach(name=>console.log('OK '+name));
    console.log(`${result.length}件成功（保存失敗のログは意図的な注入）`);
  }catch(error){
    console.error(b.events.filter(e=>e.method==='Runtime.consoleAPICalled'&&e.params.type==='error').slice(-6).map(e=>e.params.args.map(a=>a.description||a.value)));throw error;
  }finally{await b.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
